const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = (name) => fs.readFileSync(path.join(root, name), 'utf8');
const css = read('preview/preview.css').replace(':root {', ':host {') + '\n' + read('extension/src/panel-extra.css');
const markup = read('extension/src/panel.html');
fs.writeFileSync(path.join(root,'extension/src/view-bundle.js'), `// Generated by npm run build.\nglobalThis.FeigeView = ${JSON.stringify({css,markup})};\n`);
fs.mkdirSync(path.join(root,'extension/vendor'), {recursive:true});
for (const [source, target] of [
  ['node_modules/@mozilla/readability/Readability.js','Readability.js'],
  ['node_modules/@mozilla/readability/LICENSE.md','Readability.LICENSE.md'],
  ['preview/vendor/lucide.min.js','lucide.min.js'],
  ['preview/vendor/lucide.LICENSE','lucide.LICENSE']
]) fs.copyFileSync(path.join(root,source),path.join(root,'extension/vendor',target));
console.log('Built Feige local assets.');
